### ISSUE TITLE
issues with nexus as output file

### ISSUE THREAD

**Issue by lcgraber** [marekborowiec/spruceup#14]
hi, I am having an issue where i am trying to get a nexus output (to use in swsc-en) but i have been unable to after several tries. this is the terminal output + error message that I have been receving: 
python -m spruceup /home/lcg65/Desktop/PogoUCE/spruceup_config_july_13_2023.conf
2023-07-13 15:52:19,826 - Parsing alignment /home/lcg65/Desktop/PogoUCE/mafft-nexus-internal-trimmed_july_12_2023_gblocks-clean-75p-swsc-edit.nexus...
2023-07-13 15:52:29,724 - Did not find guide tree, continuing ...
2023-07-13 15:52:29,725 - Splitting into size-20 windows with 15 overlap ...
100%|████████████████████████████████████████████████████████████████████████████████████████████████| 336844/336844 [1:45:57<00:00, 78.23it/s]
2023-07-13 17:39:21,534 - Writing distances to file uncorrected-distances-20window-15overlap.json ...
2023-07-13 17:43:32,422 - Used 14270.68 MB memory
2023-07-13 17:43:32,422 - Finding outliers for 0.95 lognorms cutoff ...
2023-07-13 17:45:17,936 - Sites removed: 3081165
2023-07-13 17:45:17,936 - Removed 1.09% of sites at cutoff of 0.95 lognorms
2023-07-13 17:45:18,073 - Wrote report 0.95_lognorms-cutoff-spruceup_report_july_13_2023.txt
Traceback (most recent call last):
  File "/home/lcg65/miniconda3/envs/spruceup/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lcg65/miniconda3/envs/spruceup/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lcg65/miniconda3/envs/spruceup/lib/python3.6/site-packages/spruceup/__main__.py", line 184, in <module>
    main()
  File "/home/lcg65/miniconda3/envs/spruceup/lib/python3.6/site-packages/spruceup/__main__.py", line 177, in main
    valid_input_dict['data_type'],
  File "/home/lcg65/miniconda3/envs/spruceup/lib/python3.6/site-packages/spruceup/__main__.py", line 116, in output_loop
    trimmed_alignment, out_format, cutoff_trimmed_aln_fname, data_type
  File "/home/lcg65/miniconda3/envs/spruceup/lib/python3.6/site-packages/spruceup/aln_writing.py", line 146, in write_alignment_file
    of.write(print_nexus(alignment_dict, data_type))
  File "/home/lcg65/miniconda3/envs/spruceup/lib/python3.6/site-packages/spruceup/aln_writing.py", line 69, in print_nexus
    if data_type == "aa" or command == "translate":

I am running Python 3.6.13 remotely using a Linux machine (RB HPC/SM Xeon E7 4800 2U 112 cores; 1024GB RAM; 12TB HDD) via my university's computing cluster. I have used spruceup successfully many times before this way, but only with .phylip input and .fasta output. I also tried using a .phylip file as input but it would also not output as .nexus.

I have also attached my .conf file (changed to .txt for GitHub) here. Thank you!

[spruceup_config_july_13_2023.txt](https://github.com/marekborowiec/spruceup/files/12051282/spruceup_config_july_13_2023.txt)

**Comment by marekborowiec** [comment]
Fixed with newest release
