### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lPiacentini** [marekborowiec/spruceup#17]
**Describe the bug**
I am not able to install Spruceup, I tried on different machines and with different versions of python, but I always get the same error. I tried the installation by pip and by cloned. I always install it in a new conda environment. 

**To Reproduce**
1. pip install spruceup or git clone https://github.com/marekborowiec/spruceup.git
2. clean, created following the instructions
3. setup.py:33: SetuptoolsDeprecationWarning
4. none
5. /tmp/pip-install-3noaki1u/matplotlib_3a87d62c3e3d476b86d35da50c0f903d/setup.py:33: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!

              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
              ********************************************************************************

      !!
        from setuptools.command.test import test as TestCommand
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-3noaki1u/matplotlib_3a87d62c3e3d476b86d35da50c0f903d/setup.py", line 225, in <module>
          msg = pkg.install_help_msg()
        File "/tmp/pip-install-3noaki1u/matplotlib_3a87d62c3e3d476b86d35da50c0f903d/setupext.py", line 650, in install_help_msg
          release = platform.linux_distribution()[0].lower()
      AttributeError: module 'platform' has no attribute 'linux_distribution'
      IMPORTANT WARNING:
          pkg-config is not installed.
          matplotlib may not be able to find some of its dependencies
      ============================================================================
      Edit setup.cfg to change the build options

      BUILDING MATPLOTLIB
                  matplotlib: yes [3.0.3]
                      python: yes [3.8.19 (default, Mar 20 2024, 19:58:24)  [GCC
                              11.2.0]]
                    platform: yes [linux]

      REQUIRED DEPENDENCIES AND EXTENSIONS
                       numpy: yes [version 1.24.4]
            install_requires: yes [handled by setuptools]
                      libagg: yes [pkg-config information for 'libagg' could not
                              be found. Using local copy.]
                    freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                              could not be found.  You may need to install the
                              development package.]
                         png: no  [pkg-config information for 'libpng' could not
                              be found.]
                       qhull: yes [pkg-config information for 'libqhull' could not
                              be found. Using local copy.]

      OPTIONAL SUBPACKAGES
                 sample_data: yes [installing]
                    toolkits: yes [installing]
                       tests: no  [skipping due to configuration]
              toolkits_tests: no  [skipping due to configuration]

      OPTIONAL BACKEND EXTENSIONS
                         agg: yes [installing]
                       tkagg: yes [installing; run-time loading from Python Tcl /
                              Tk]
                      macosx: no  [Mac OS-X only]
                   windowing: no  [Microsoft Windows only]

      OPTIONAL PACKAGE DATA
                        dlls: no  [skipping due to configuration]

      ============================================================================
                              * The following required packages can not be built:
                              * freetype, png
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Expected behavior**
Install the program

**Screenshots**

**Desktop (please complete the following information):**
 - Distributor ID: Ubuntu 22.04.3 LTS jammy
 - Python version [e.g. 3.6.5], I try with Python 3.8.19, 3.10.12 and 3.6
 - `spruceup` version [e.g. 2019.2.2]
- Conda and/or pip version conda 24.7.1 pip 24.2 

**Additional context**

**Comment by BenMcDUON** [comment]
Hi lPiacentini, Did you find a way to get around the setup.py issue?

I'm receiving a similar error:

(spruceup) C:\Users\c3324879\Downloads\spruceup>python -m pip install spruceup
Requirement already satisfied: spruceup in c:\programdata\anaconda3\envs\spruceup\lib\site-packages\spruceup-2024.8.20.post1-py3.12.egg (2024.8.20.post1)
Collecting matplotlib==3.0.3 (from spruceup)
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      C:\Users\c3324879\AppData\Local\Temp\1\pip-install-p_3m1rix\matplotlib_dc66415a69ee43119ce07d496f814a19\setup.py:33: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!

              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.
              ********************************************************************************

      !!
        from setuptools.command.test import test as TestCommand
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 35, in <module>
        File "C:\Users\c3324879\AppData\Local\Temp\1\pip-install-p_3m1rix\matplotlib_dc66415a69ee43119ce07d496f814a19\setup.py", line 53, in <module>
          __version__ = versioneer.get_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\c3324879\AppData\Local\Temp\1\pip-install-p_3m1rix\matplotlib_dc66415a69ee43119ce07d496f814a19\versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\c3324879\AppData\Local\Temp\1\pip-install-p_3m1rix\matplotlib_dc66415a69ee43119ce07d496f814a19\versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\c3324879\AppData\Local\Temp\1\pip-install-p_3m1rix\matplotlib_dc66415a69ee43119ce07d496f814a19\versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Regards,
Ben

**Comment by shawn53a** [comment]
Hello there Ben, 

I ran into a similar issue. To get around it I downloaded python version 3.6.10 from the python website. I made sure to use `sudo make altinstall` during the configuration process as to not overwrite my primary python.

I then created and opened a virtual environment with python 3.6.10:
`python3.6 -m venv env`

Once I entered the virtual environment, I ran `pip install spruceup` and it seemed to install correctly!

**Comment by shawn53a** [comment]
Hi Ben! 

I ran into a similar issue. I think the problem is that your trying to install using python 3.12. You should use python 3.6 or an early version of 3.7. These are the only versions of python that spruceup will work with.

I installed this in a conda environment: 
$ conda create -n test python=3.6

Once I entered the environment I used the:
pip install spruceup

This worked for me! I hope it helps!
