### ISSUE TITLE
Plotting when using 'means' criterion does not work

### ISSUE THREAD

**Issue by mkweskin** [marekborowiec/spruceup#8]
When using the 'mean' criterion, I get this error at the plotting phase:

```
2019-11-12 09:13:00,583 - Plotting distance distributions and cutoffs
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/spruceup/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/miniconda3/envs/spruceup/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/miniconda3/envs/spruceup/lib/python3.6/site-packages/spruceup-2019.2.3-py3.6.egg/spruceup/__main__.py", line 184, in <module>
  File "/home/user/miniconda3/envs/spruceup/lib/python3.6/site-packages/spruceup-2019.2.3-py3.6.egg/spruceup/__main__.py", line 177, in main
  File "/home/user/miniconda3/envs/spruceup/lib/python3.6/site-packages/spruceup-2019.2.3-py3.6.egg/spruceup/__main__.py", line 123, in output_loop
  File "/home/user/miniconda3/envs/spruceup/lib/python3.6/site-packages/spruceup-2019.2.3-py3.6.egg/spruceup/spruceup.py", line 443, in plotting_wrapper
TypeError: plot_taxon_dists() missing 1 required positional argument: 'manual_cutoff'
```

I was able to fix this by changing line 443 of spruceup.py to:
`plot_taxon_dists(all_taxa_dists, taxon, method, criterion, cutoffs, manual_cutoff,)`

😸

**Comment by marekborowiec** [comment]
Thank you for noticing this! It should be fixed now.
